### ISSUE TITLE
Link to Answers and Community from Ignition site

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/docs#101]
From today's community meeting:

It would be nice to add links to websites like [Gazebo Answers](https://answers.gazebosim.org) and [Gazebo Community](https://community.gazebosim.org/) to the [Ignition](https://ignitionrobotics.org/) website (perhaps we should just make sure that all relevant links on the gazebo classic website are also on the ignition website).

This change will need to be made on this private repository: https://gitlab.com/ignitionrobotics/web/web

**Comment by adlarkin** [comment]
I'm closing this since the website is now udpated.
