### ISSUE TITLE
Document ABI contract used in Ignition Libraries versioning

### ISSUE THREAD

**Issue by traversaro** [ignitionrobotics/docs#113]
As part of the effort in packaging ignition libraries in [conda-forge](https://conda-forge.org/), the topic of ABI compatibility in ignition libraries emerged as conda has quite advanced support to specify runtime compatibility of the generated binaries. To argue which compatibility rules made sense for Ignition Libraries, I wanted to provide to the other packages some references, but I could not find any (just some references in other document, see https://github.com/ignitionrobotics/docs/search?q=ABI). 

I would say that the general rule is:
* Binaries compiled against ignition-lib version x.y.z can run without problems with a compile ignition-lib with the same major version and that has a version >= x.y.z .

But it would be nice to a have a clear reference, to clarify corner cases (see for example https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/12#issuecomment-720069113, where we argue if a binary compiled against ignition-lib 1.11.2 can run with a binary 1.11.0, and I would say that it is not possible as in release 1.11.2 new symbols can be introduced w.r.t. release 1.11 .

**Comment by traversaro** [comment]
cc @wolfv @Tobias-Fisher @j-rivero

**Comment by chapulina** [comment]
> Binaries compiled against ignition-lib version x.y.z can run without problems with a compile ignition-lib with the same major version and that has a version >= x.y.z .

That's correct.

> if a binary compiled against ignition-lib 1.11.2 can run with a binary 1.11.0, and I would say that it is not possible as in release 1.11.2 new symbols can be introduced w.r.t. release 1.11 .

You're right, the ABI compatibility is only when going from a lower version to a higher version, but not the other way around.

Note though that we (strive to) bump the minor when adding new API. So in your specific example, where only the patch version was bumped, ABI compatibility can be assumed in both directions.

---

Thank you for bringing this up. We mention the use of SemVer in a couple places:

* https://ignitionrobotics.org/docs/all/releases
* https://ignitionrobotics.org/docs/all/roadmap#feature-roadmap

But strictly speaking, SemVer is only about API, not ABI. So I think we can state our ABI policy explicitly in one of those 2 places and make the corner cases you mentioned clear as well.

**Comment by j-rivero** [comment]
> But it would be nice to a have a clear reference, to clarify corner cases (see for example [conda-forge/libignition-fuel-tools-feedstock#12 (comment)](https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/12#issuecomment-720069113), where we argue if a binary compiled against ignition-lib 1.11.2 can run with a binary 1.11.0, and I would say that it is not possible as in release 1.11.2 new symbols can be introduced w.r.t. release 1.11 .

World if full of interesting corner cases I've never though before. I agree with @chapulina comments here.

**Comment by chapulina** [comment]
I tried to concisely document this on https://github.com/ignitionrobotics/docs/pull/183, I hope it's clear enough.

**Comment by traversaro** [comment]
Thanks, I think that docs solve the issue!
