### ISSUE TITLE
Document macOS caveats on binary installation tutorial

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/docs#116]
The install tutorial for macOS from source lists caveats and extra tips to get Ignition to work:

https://ignitionrobotics.org/docs/citadel/install_osx_src

While the binary install tutorial suggests that everything will just work out of the box:

https://ignitionrobotics.org/docs/citadel/install_osx

We should make sure that users installing from binaries are aware of caveats and any extra steps needed.

**Comment by ahcorde** [comment]
- https://github.com/ignitionrobotics/docs/pull/150
 - https://github.com/ignitionrobotics/docs/pull/151

**Comment by chapulina** [comment]
Thanks, @ahcorde . Are you working on more PRs or do these cover everything?

CC @scpeters

**Comment by ahcorde** [comment]
These are the two issues that I have found. Maybe I can add the `gazebo_scene_viewer` as an alternative to visualize what's going on in the scene.

What do you think ?

**Comment by chapulina** [comment]
I think the main problem is the sentence "_All libraries should be ready to use and the ign gazebo app ready to be executed._", which gives the impression that everything should just work. I think we should document in those tutorials that the 3D scene doesn't work and that `ign gazebo` should only be run headless, see https://github.com/ignitionrobotics/ign-gazebo/pull/477/ as a reference.

We should document this for Citadel, Dome and Edifice.

**Comment by chapulina** [comment]
I see this is already documented
