### ISSUE TITLE
[Ubuntu] When installing from source, installing dependencies also tries to install ignition packages

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [ignitionrobotics/docs#119]
When trying to install ignition from source on linux (Ubuntu 20.04) we have to install the dependencies before compiling.
Following this tutorial: https://ignitionrobotics.org/docs/edifice/install_ubuntu_src#install-dependencies

The issue is that the command to list and install the dependencies 
`sudo apt -y install \
  $(sort -u $(find . -iname 'packages-'$SYSTEM_VERSION'.apt' -o -iname 'packages.apt') | tr '\n' ' ')`
It also list and tries to install ignition libraries (that we don't have since we are trying to install frrom source)
Plus if we didn't add gazebo/ubuntu-nightly to our souce-list some packages are simply not available:
- libignition-gazebo5-dev
- libignition-gui5-dev
- libignition-rendering5-dev
- libignition-sensors5-dev

Thus the command line should not list ignition libraries
ex:
`sudo apt -y install \
  $(sort -u $(find . -iname 'packages-'$SYSTEM_VERSION'.apt' -o -iname 'packages.apt') | grep -v ignition | tr '\n' ' ')`

I couldn't find any issue related to this, so I am not sure. But it doesn't sound right to install libraries you are trying to compile.

**Comment by chapulina** [comment]
Thank you for ticketing the issue. That's a good point, those `package.apt` files were created with the goal of supporting a single library being installed from source.

Adding `--ignore-missing` to the command would allow it to continue even without nightlies. But for released versions (up to Dome), the stable Ignition dependencies would still be installed.
