### ISSUE TITLE
releases: Page not rendering?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ignitionrobotics/docs#28]
I tried viewing the following page:
<https://ignitionrobotics.org/docs/releases>

However, this is what I see:
> <img src="https://user-images.githubusercontent.com/26719449/83339109-73380000-a298-11ea-9d62-0014bec06eb0.png" height="200px"/>

Javascript error from Developer console:
```
ERROR TypeError: "a.docsInfo.pages[a.version] is undefined"
```

Browser: Firefox 76.0.1
OS: Ubuntu 18.04

**Comment by chapulina** [comment]
Yeah, the correct URL is https://ignitionrobotics.org/docs/all/releases

I remember there were links missing the `/all/` but I can't find them now. Do you remember how you got to this link? The link on the [Ignition Documentation](https://ignitionrobotics.org/docs) page looks correct.

**Comment by EricCousineau-TRI** [comment]
Same as here: https://github.com/ignitionrobotics/docs/issues/29#issuecomment-636953759

I currently don't remember how I got to it two days ago :(

**Comment by chapulina** [comment]
I think I found one place where these links can be coming from: other pages. Like the Roadmap's link to the Releases page is wrong:

https://ignitionrobotics.org/docs/all/roadmap

I think it just needs to be updated here:

https://github.com/ignitionrobotics/docs/blame/master/roadmap.md#L49

There are probably others in the same situation.

**Comment by EricCousineau-TRI** [comment]
Ah, maybe that was it - thanks!!!
