### ISSUE TITLE
"Latest installation tutorial" link goes to Acropolis

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/docs#4]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/docs/issues/4)) by MaryaB (Bitbucket: [MaryaB](https://bitbucket.org/%7Bde4d1ed8-dd76-4970-82ff-cbe57e3fb6a7%7D/), GitHub: [maryab-osr](https://github.com/maryab-osr)).**

----------------------------------------
This section in the release-agnostic Get Started guide: [https://ignitionrobotics.org/docs/all/getstarted#step-1-install](https://ignitionrobotics.org/docs/all/getstarted#step-1-install)

I’m not sure how /docs/**latest**/install is configured: [https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/docs/annotate/default/get\_started.md?at=default&fileviewer=file-view-default#get\_started.md-14](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/docs/annotate/default/get_started.md?at=default&fileviewer=file-view-default#get_started.md-14)

**Comment by chapulina** [comment]
During today's meeting someone brought up that this may be just a matter of reordering the releases here:

https://github.com/ignitionrobotics/docs/blob/11fec13f8dce0cf2230a3ed620ba5f7edb0473d7/index.yaml#L42-L45

**Comment by ahcorde** [comment]
This should be fixed with this PR https://github.com/ignitionrobotics/docs/pull/60

**Comment by ahcorde** [comment]
Deployed
