### ISSUE TITLE
Add changelog links to documentation

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/docs#5]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/docs/issues/5)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
Add links to the changelog of each library for each Ignition release on the `release-features.md` page.
Need to wait until we migrate away from bitbucket.

**Comment by ahcorde** [comment]
PR https://github.com/ignitionrobotics/docs/pull/63

**Comment by ahcorde** [comment]
The PR merged
