### ISSUE TITLE
Change PR examples in contributing.md to GitHub examples

### ISSUE THREAD

**Issue by maryaB-osr** [ignitionrobotics/docs#9]
"13. Make small pull requests" in the [Contributing Code section](https://github.com/ignitionrobotics/docs/blob/c1a1d96e26986761394c1d807a7a7c4d75bd5fe4/contributing.md#contributing-code) of `contributing.md` uses bitbucket PRs as examples. Once we have some PRs up for Ignition those links should be switched out

**Comment by ahcorde** [comment]
@maryaB-osr  https://github.com/ignitionrobotics/docs/pull/59
