### ISSUE TITLE
Move troubleshooting to its own page

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/docs#92]
We have some troubleshooting steps for Linux here: https://ignitionrobotics.org/docs/citadel/install_ubuntu_src#troubleshooting and for Mac here: https://ignitionrobotics.org/docs/citadel/install_osx_src#troubleshooting

Although the troubleshooting is on the source install pages, they also apply to the binary install pages. So I think we should move them to separate pages and link to that at the end of the installation tutorials.

**Comment by claireyywang** [comment]
shamelessly taking this for Hacktoberfest :laughing:
