### ISSUE TITLE
Explain new toolbar on "Understanding the GUI"

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/docs#93]
We have a new grey toolbar with transform controls and simple shapes, from Citadel onwards. The GUI tutorial should explain that toolbar. 

https://ignitionrobotics.org/docs/dome/gui

Note that the transform controls are explained in detail on "Manipulating Models", so we shouldn't duplicate that information, just mention that the plugin is there.

https://ignitionrobotics.org/docs/dome/manipulating_models

The shapes insertion bar is not documented yet and needs documentation.

**Comment by claireyywang** [comment]
Hacktoberfest! :beer:
