### ISSUE TITLE
Update Citadel screenshots

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/docs#94]
Since the tutorials were written, the GUI has been updated with new colors and a toolbar on the top. It would be nice to update the screenshots on Citadel. The ones on Dome are already up-to-date.

See for example:

* Citadel: https://ignitionrobotics.org/docs/citadel/manipulating_models
* Dome: https://ignitionrobotics.org/docs/dome/manipulating_models

**Comment by claireyywang** [comment]
:beer:
